routes:

collections:
  /:
    permalink: /{slug}/
    template: index
    filter: tag:-podcast+tag:-book

  /podcast/:
    permalink: /podcast/{slug}/
    template: podcast
    filter: primary_tag:podcast
    data: tag.podcast

  /book/:
    permalink: /book/{slug}/
    template: tag
    filter: primary_tag:book
    data: tag.book

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
